### ISSUE TITLE
Recent changes

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM_APP_stemp_abw#10]
Hey @4lm,

I implemented several changes which I just merged to `dev`.
A quick overview:

1. Allow for several table lists (first and last panel). This affected a lot of stuff, e.g. forms, widgets, templates, JS and CSS. As there will be well-known, defined number of those lists and due to lack of time, I implemented this in a quite non-generic way.
2. New models (a recent dump is located in your Temp dir)
3. New region layers
4. Proxy model now can access associated models/tables, fields are defined using property decorators (see `RegMunStats`)
5. Layer now can use a common proxy model (especially `RegMunStats`) which is defined in `layers_*.cfg` via param `model =`.
This leads to another problem: For n layers, the layer is loaded n times with the very same data. I opened a separate issue on this: #11 

We still have to elaborate how the popups/DetailViews get their data. But as we decided on layer-specific popups, I do not see large problems here.

**Comment by 4lm** [comment]
> 4. Proxy model now can access associated models/tables, fields are defined using property decorators (see `RegMunStats`)

Nice, especially, that we can also now dynamically create values from other tables, e.g.: 

```
@property
    def gen_energy_re_per_capita(self):
        return round(self.gen_energy_re * 1e3 / self.mundata.pop_2017, 1)
```

**Comment by 4lm** [comment]
> We still have to elaborate how the popups/DetailViews get their data. But as we decided on layer-specific popups, I do not see large problems here.

Yes, I also don't see large problems here.
