### ISSUE TITLE
Background map not loaded

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM_APP_stemp_abw#113]
Background map is not loaded due to limited number of tiles ([750k](https://www.mapbox.com/pricing/)) in the free account that can be loaded from mapbox. This limit is reached by now.

Options
1. Remove mapbox tiles
2. Create new account with another 750k tiles (would have to be done again in the future...)

To prevent future problems I'll go for 1 and set OSM as new default.

**Comment by Bachibouzouk** [comment]
I agree with proposed solution

**Comment by nesnoj** [comment]
Although the standard OSM tiles do not look as good as the mapbox ones, StEmp ABW now uses those ones for sake of a quick fix. If you have an open alternative which looks better, I'm interested too :).
