### ISSUE TITLE
Map layers clickable while loading

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM_APP_stemp_abw#13]
During loading process, map layers that are already loaded can be accessed/clicked which should be prevented.

**Comment by 4lm** [comment]
Hi @nesnoj,

I stumbled over a solution for this and thought, I know a place where there is good use for this :)

CSS pointer-events: https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events

If set to `none`, it will make the selected element in the DOM non-clickable! Has a support of 96,75%: https://caniuse.com/#feat=pointer-events

**Comment by nesnoj** [comment]
Nice - if it works for leaflet, go ahead..

**Comment by 4lm** [comment]
:thinking: It doesn't work, I tried:

- setting point-canvas to none (no effect)
- using an overlay (overlay is replaced during loading process by leaflet map, hence no effect)
- disabling and enabling leaflet interactivity: https://gis.stackexchange.com/a/54925 (no effect)

It's more tricky as I thought! Any ideas?

**Comment by nesnoj** [comment]
If there's no fast solution, please close this @4lm

**Comment by 4lm** [comment]
OK!
