### ISSUE TITLE
HC in popup fixed, but sporadic JS error

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM_APP_stemp_abw#18]
I found the error why the HCs are not loaded:

The problem was, that you were using the same visualizations in popups as well as in the results. Hence, you always have 2 DIVs with the same id (e.g. "hc_3") for each vis. The JS code is subsequently applied to the 2nd DIV instead of (as intended) to the 1st one.
If you delete the result HCs, it works. I created a commit in [your branch](https://github.com/rl-institut/WAM_APP_stemp_abw/tree/feature/specialize-popups): 03f3e8131c824e1faa3dae6b554ff2e489602b17
So just create separate vis for the popups and it should work out.

The chart in the popup is way too large and not conform with the popup style but this can be fixed, at least it works now. (It might be a good idea to pass some style etc. [args](https://api.highcharts.com/highcharts/) when creating instances for popups to override the default styling).

**BUG**
Sporadically, the popup HC does not work since the HC params in the JS code are empty. I couldn't figure out the reason or a pattern. In the last commit 6337ffedb14a3eb58445e91f959cdcee9db20fd3, I added echoing of the JS code to debug. The screenie below shows it (1st click doesn't work -> HC params empty, 2nd does -> JS correct)

![stemp_abw_popup_jserror1](https://user-images.githubusercontent.com/15910173/53948408-07340f80-40c8-11e9-9809-d18fdd325852.png)

Any clue?

**Comment by 4lm** [comment]
Hi @nesnoj,

thank you for the fix and the explanation! I will have a look at it.

Yes, the behavior of the bug (1st click doesn't work -> HC params empty, 2nd does -> JS correct) seems odd. I will also have a look at it as well.

**Comment by nesnoj** [comment]
Solved via #19
