### ISSUE TITLE
Infobox behind panel

### ISSUE THREAD

**Issue by 4lm** [rl-institut/WAM_APP_stemp_abw#25]
Hi @nesnoj,

I pulled the new version (dev branch) and integrated the db dump, it works and looks very nice - yay!

I also found a behavior which wasn't not observed before, the infoboxes are now behind the panel, see following image:

![image](https://user-images.githubusercontent.com/3404313/55151552-c8d1c380-514e-11e9-9ff6-34ae6dbdb4d7.png)

Is this behavior maybe fixed in the feature/simulation branch?

**Comment by nesnoj** [comment]
Uh, that's odd. I do not I have this problem nor the participants of yesterday's workshop.

This is the z-indices list of special elements:

| class/id | what is it | z-index |
| ------------- | ------------- | ----- |
|.top-bar|top menu|999999999999999999|
|**.tooltip**|**tooltip**|**99999999999999999**|
|.loader-wrapper|overlay while loading|9999999999999999|
|.reveal-overlay|popup (non-leaflet)|99999999999999|
|**.off-canvas-wrapper**|**left panel menu**|**999999999**|
|.off-canvas-content|map+footer|999999|
|.top-bar ul|menu popup|999999|
|#simulation-save-btn|save btn|99999|

The tooltip should be on top of the left panel menu.
Interestingly, the [z-index is an integer](https://www.w3.org/TR/CSS21/visuren.html#z-index) so the max. value in modern browsers is 2^31-1 = 2147483647. I don't know why @bmlancien used too large values here (maybe he assumed the max to be 2^64).

I'd assume that your browser sets the `tooltip`'s z-index value - which exceeds integer - to the max ([as described here](https://stackoverflow.com/questions/491052/minimum-and-maximum-value-of-z-index/856569)) of 2147483647 which is larger than the one of `.off-canvas-wrapper`, hence the tooltip should be on top. No idea why this does not happen in your browser, could you check the index via web toolbar?

I'll modify all those values to be within int range and we can check again...

**Comment by nesnoj** [comment]
In my browser it says 99999999999999999 which is the correct value.
Could you please lookup this in your browser?

**Comment by nesnoj** [comment]
I changed the order in https://github.com/rl-institut/WAM_APP_stemp_abw/tree/fix/z-index-order-25 like this:

| class/id | what is it | z-index |
| ------------- | ------------- | ----- |
|.loader-wrapper|overlay while loading|999999999|
|.top-bar|top menu|99999999|
|**.tooltip**|**tooltip**|**9999999**|
|.reveal-overlay|popup (non-leaflet)|9999999|
|**.off-canvas-wrapper**|**left panel menu**|**999999**|
|.top-bar ul|menu popup|99999|
|#simulation-save-btn|save btn|99999|
|.off-canvas-content|map+footer|9999|

Please check if the problem persists.
- If so, you may want to try a [plugin](https://stackoverflow.com/a/42047500/6419458) which shows the element by z-index to find out where the order is incorrect.
- If not, please merge the branch into dev.

**Comment by 4lm** [comment]
Mhhh,
 
I'm confused! It's working now, without pulling your fix:

![image](https://user-images.githubusercontent.com/3404313/55162316-d778a480-5167-11e9-999e-a56252427bbb.png)

I'm sorry for this false positiv and therefore the extra work you put into this issue, it looked like a bug to me, maybe it was a caching issue?

What do you think? Shall I still pull the fix commit (fix/z-index-order-25), test and merge it (into dev) for the MAX = 2^31-1 issue? Or just let it sit there and only merge it, if we encounter this behavior a second time and can verify that it is not a caching issue ...

**Comment by nesnoj** [comment]
No worries, this had to be done anyway. I merged the fix.
