### ISSUE TITLE
Layer Map isn't reloaded properly after going back from sources

### ISSUE THREAD

**Issue by 4lm** [rl-institut/WAM_APP_stemp_abw#26]
Hi @nesnoj,

as discussed after clicking on a source in a popup the user lands on the source page, after going back to the map via the browser back button, the layer of the popup is toggled on in the panel but the layer is not active in the map.

As spoken, maybe we find a solution where the state of the layers and panel switches is preserved.

**Comment by nesnoj** [comment]
I see 2 solutions here:
1. Restore the previous state using sessions' scenario where most input values are stored. The challenging part are the dynamic results.
2. Embed the sources page in an overlay, e.g. popup

The 2nd one is way easier to implement, but let's get back to this later.

**Comment by nesnoj** [comment]
The scenario settings are reset thanks to the recent session update (cf. https://github.com/rl-institut/WAM_APP_stemp_abw/issues/43#issuecomment-501679019). As the SQ scenario is applied on each visit (also via back button), the esys controls are reset as well.

The only missing things from my point of view are the bootstrap layer switches and a warning notice.
I recommend to:
1. Simply reset all of them on visit -> set to on or off according to configs, u can make use of `show` param in layer context 
2. Add a warning similar to [error popup](https://github.com/rl-institut/WAM_APP_stemp_abw/blob/feature/layers-in-results/templates/stemp_abw/map.html#L480-L483) when the user wants to leave the tool for the sources

@4lm could you take care of this please? (only if it doesn't take u more than an hour, if it takes longer we should go for the embedded solution (see option 2 in previous post) and postpone this)

**Comment by 4lm** [comment]
@nesnoj. Please merge again the branch `feature/results-in-layers` into your working branch to fetch above commit: https://github.com/rl-institut/WAM_APP_stemp_abw/commit/31782e051269d8a7bd5700e435763bbe54d23506

Then close this issue.

As requested via email, I will add two new feature branches and issues for the work on:

1.) Improving page navigation in map view
2.) Add confirm dialog if clicking on start page link from map view

**Comment by nesnoj** [comment]
Good work :+1:
