### ISSUE TITLE
Style popups

### ISSUE THREAD

**Issue by 4lm** [rl-institut/WAM_APP_stemp_abw#28]
Hi @bmlancien and @nesnoj,

as mentioned in #22 I opened this more specific issue to talk about how to style the popups further:

Right now the popups take their styles from the baked app.css and the leaflet.css. Because of this it's a style mixture. 

@bmlancien and I already included some Foundation classes into the popup's HTML structure to be able to add some specific Foundation styles.

Right now I don't now how to handle the styling issue concretly, but see to possibilities to go (there are maybe more):

- We keep the old workflow and @bmlancien does the styling. For this he needs access to a running instance of the latest dev branch.

- We integrate the CSS workflow into the stemp_abw repo, so that we can all work on the styling and its manual tweaking in the baked app.css.

What do you think (I think a decision can wait after @nesnoj is back from holidays)?

**Comment by 4lm** [comment]
I opened a branch for the work on this: https://github.com/rl-institut/WAM_APP_stemp_abw/tree/feature/style-popup

**Comment by 4lm** [comment]
Hi @bmlancien. I have spoken to @nesnoj and we decided that I will work on the popup CSS styling concerning the popups using the given CSS workflow. So no need that you get involved at this point (maybe I have questions later on). I will start the work now.

**Comment by nesnoj** [comment]
@4lm The charts in popups look good! To achieve this, you've added a new `CUSTOM_RLI_THEME` for all charts. But now the result charts aren't properly styled anymore regarding
- design (font size etc.)
- number formats and legends

We should use different themes depending on where it is used.
I disabled it temporarily in 1ed319e0abb55e40b2bddd3ff5ef4b7da4be4d5a.

**Comment by 4lm** [comment]
Mhh, I'm not sure if you completly got what I did there:

- the standard RLI-THEME is here (WAM):  https://github.com/rl-institut/WAM/blob/dev/utils/highcharts.py#L10-L53
- The theme `CUSTOM_RLI_THEME` in visualizations/highcharts.py was newly defined by me and included by changing `class HCStemp(Highchart)` in which I added the param `use_rli_theme` (which defaults to `True`) and added a conditional: https://github.com/rl-institut/WAM_APP_stemp_abw/commit/79f5b99a9360ab6aca24107390ac5b9aa312d3bf
- You know changed my custom rli theme `CUSTOM_RLI_THEME` instead of using the standard rli theme.

I think I know where the confusion could have come from, I named the param `use_rli_theme` instead of `use_custom_rli_theme` OR `custom_rli_theme`.

I you want to use the standard theme, which was used before (defined in the WAM project), the default of `use_rli_theme` simply could be set to `False` . Sorry for setting it to True by default and by this also overwriting the used standard theme for the results charts (I checked it with the dummy charts I had in my branch and it looked good to me).

> We should use different themes depending on where it is used.

Yes, I totally agree! We could change the class in the way, that the theme has to be handed over as param and that it defaults to the standard theme of the WAM ...

**Comment by 4lm** [comment]
I just realized, that I was orienting myself at the original WAM HC class (when I changed the __init__ method of the subclass of HC) which implemented it  the way I described in my above comment: https://github.com/rl-institut/WAM/blob/dev/utils/highcharts.py#L60-L66

Maybe we could find a way to change the code in the WAM project so that it adds this functionality there, but I don't know if this would conflict with other projects ...

**Comment by nesnoj** [comment]
@4lm Beside the text formatting some I needed a different aspect ratio for the result charts. Therefore, in 0460f7ede1152371b2f00f6ed94b0e2f8a4a3393 I've split the custom RLI theme into two: one for the popups and one for the results. The param `theme` must be explicitly set when creating a popup HC. I adjusted your detail views accordingly.
(not sure if a full merge into your branch is a god idea, you may want to cherry-pick)

(by mistake, I mentioned #22 in the commit but it is actually this issue)

**Comment by nesnoj** [comment]
I think we're done here, thx!
