### ISSUE TITLE
Refactor and document popup-related code 

### ISSUE THREAD

**Issue by 4lm** [rl-institut/WAM_APP_stemp_abw#29]
Hi @nesnoj,

as mentioned in #22 in this issue I wan't to discuss which popup-related code to refactor and to further document.

For the work on this I opened a branch: https://github.com/rl-institut/WAM_APP_stemp_abw/tree/feature/refactor-document-popup-related-code

First, I will refactor and document the code (and related code) in views/detail_views.py - I think this is necessary, because the code became quite bloated (not DRY) and does things in a complicated way, which will hinder future work.

**Comment by nesnoj** [comment]
I appreciate that!
The code is...a "slightly" redundant. Do you plan to make it more generic?

**Comment by 4lm** [comment]
Yes, I'm about to refactor views/detail_views.py. I did first steps in this direction last week and will try to further refactor the use of classes in views/detail_views.py to make it more generic.

**Comment by 4lm** [comment]
Hi @nesnoj,

the refactoring of popup-related code is pretty much done, now:

- each popup with a chart has 1 corresponding view class instead of 3 view classes. Ergo, every detail view consists of one single class now.
- all URL patterns in urls.py are generic now (especially for HTML and for JS popup views)
- there is no whitelist in map_functions.js anymore. The choice whether a popup uses a chart or not is now fully generic and determined automatically.

Next time I would like to write some basic tests and add more documentation. I think the basic tests are a good idea, because of the generic approach I added dependencies, which are predestined for testing, for example the generic approach in map_functions.js tests if there is an id which starts with "hc_'

**Comment by 4lm** [comment]
Pull request is merged, will close this issue!
