### ISSUE TITLE
Documentation on RTD

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM_APP_stemp_abw#30]
An important milestone are the app docs.
I created a structural draft in branch [`add-sphinx-docs`](https://github.com/rl-institut/WAM_APP_stemp_abw/tree/add-sphinx-docs) and added it to RTD: https://stemp-abw.readthedocs.io , feel free to amend!

**API docs**
There're some problems with the API docs that need to be solved, see https://github.com/rl-institut/WAM/issues/47.
Also, we must come to a decision on app naming, https://github.com/rl-institut/WAM/issues/50 prior to further steps here

**Comment by nesnoj** [comment]
JS API docs should be included too, [sphinx-js](https://pypi.org/project/sphinx-js/) seems to be appropriate here..

**Comment by 4lm** [comment]
sphinx-js looks nice! I also just added German spell checking to Pycharm.

- [a good way seems](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000123930-German-Spell-Checker-dictionary) to just download a .dic file: http://www.winedt.org/dict.html (I downloaded "German (new sp)")
- then unzip and load in `File > Settings > Editor > Spelling`

Worked for me!

**Comment by nesnoj** [comment]
Regardless of your warning, I added some stuff to the dev part.
Not sure if the [graphviz extension](https://build-me-the-docs-please.readthedocs.io/en/latest/Using_Sphinx/UsingGraphicsAndDiagramsInSphinx.html) is the way to go but worth testing..

**Comment by 4lm** [comment]
> Regardless of your warning, I added some stuff to the dev part.
No problem :) iPull

**Comment by nesnoj** [comment]
As just mentioned, it'd be great if you'd continue working on the dev part of the docs

**Comment by 4lm** [comment]
> As just mentioned, it'd be great if you'd continue working on the dev part of the docs

Hi @nesnoj, as mentioned yesterday f2f, I'm on it. I created an extra branch: https://github.com/rl-institut/WAM_APP_stemp_abw/tree/feature/improve-docs

Feel, free to also commit on this branch ...

**Comment by nesnoj** [comment]
Nice :+1: 
I merged into dev and other current branches to make sure everything uses the latest base.

**Comment by nesnoj** [comment]
@4lm The WAM install docs will be updated by @henhuy shortly. As soon as this will have taken place, could you please revise and harmonize our [installation docs](https://github.com/rl-institut/WAM_APP_stemp_abw/blob/feature/improve-docs/doc/installation_and_setup.rst)? Thx!

**Comment by nesnoj** [comment]
The API docs could be fixed in and lives at [feature/sphinx_apidocs](https://github.com/rl-institut/WAM_APP_stemp_abw/tree/feature/sphinx_apidocs), discussion see https://github.com/rl-institut/WAM/pull/82.

Reminder for me: Set [RTD requirement](https://github.com/rl-institut/WAM_APP_stemp_abw/blob/2fddc3f2db138f8271a91ad62b3fe1d9e59af6c5/doc/requirements.txt#L1) from feature to master branch after [WAM release v0.1.3](https://github.com/rl-institut/WAM/issues/88).

**Comment by nesnoj** [comment]
> Hi @nesnoj, as mentioned yesterday f2f, I'm on it. I created an extra branch: https://github.com/rl-institut/WAM_APP_stemp_abw/tree/feature/improve-docs
> 
> Feel, free to also commit on this branch ...

I'll delete this branch as it is too unspecific (current doc state is now on dev). Doc improvements should be part of every feature branch, e.g. the fixture install instructions should be part of #77
