### ISSUE TITLE
Improve page navigation in map view

### ISSUE THREAD

**Issue by 4lm** [rl-institut/WAM_APP_stemp_abw#55]
Branch: https://github.com/rl-institut/WAM_APP_stemp_abw/tree/feature/improve-navigation

**Comment by 4lm** [comment]
@nesnoj, I just added - for testing - new tabs links in:

Datenschutz (Header)
Kontakt (Menu)
Impressum (Menu)
Quellen (Menu|Popups)
Annahmen (Menu)

and I really hate it! It destroys the whole navigation flow. I would like to only add new tab links in the sources links in popups ...

What do you think?

**Comment by 4lm** [comment]
@nesnoj,

please review above commits and merge them into your working brach, if you like what you see :wink:

Good luck next week :heart:

**Comment by nesnoj** [comment]
Cheers!
I've two change requests:
1. Show warning not only when clicking on start page but also for the links to Impressum, Sources, Kontakt, Datenschutz (and change the warning text accordingly)
2. Could you please center everything in the warning popup?
![stemp_abw_warnung](https://user-images.githubusercontent.com/15910173/59932368-4a33ac00-9447-11e9-8403-aea76b52ce09.png)

**Comment by nesnoj** [comment]
2. is fixed in d5fd052b93cbb896dd22fd56c4211e2157fb20b3

**Comment by 4lm** [comment]
> ...requests: Show warning not only when clicking on start page but also for the links to Impressum, Sources, Kontakt, Datenschutz (and change the warning text accordingly)

OK. Will do!

**Comment by nesnoj** [comment]
Done in #70, cheers @4lm!
