### ISSUE TITLE
enabled layers not shown on startup

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM_APP_stemp_abw#6]
Thanks for the beautifully colored map!

I stumbled across one issue after the choropleth merge:
On startup of the app, no layer is shown, even if it is set to `show = 1` and therefore enabled in the layer tab.
Could you please fix this? You can do it directly in dev...

**Comment by 4lm** [comment]
Hi @nesnoj,

should be fixed in the other pull-request #5, you merged right now.

Regards,
Alexis

**Comment by 4lm** [comment]
Ah interesting,

its not OK in dev but in my branches, I will have a deeper look.

Regards,
Alexis

**Comment by nesnoj** [comment]
Thanks.
The merge was rather complicated, I hope I didn't mess things up...

**Comment by 4lm** [comment]
Should be fixed now!

**Comment by nesnoj** [comment]
Cheers!
