### ISSUE TITLE
Attribution for street layer

### ISSUE THREAD

**Issue by christian-rli** [rl-institut/WAM_APP_stemp_abw#67]
I noticed that there is a nice looking street layer from mapbox in the app. Mapbox wants you to  [attribute them](https://docs.mapbox.com/help/how-mapbox-works/attribution/). We noticed this in FredApp (https://github.com/rl-institut/WAM_APP_FRED/issues/95). Now I know where those lines of code came from :)

**Comment by 4lm** [comment]
@christian-rli,

thanks for hint!

Where the token came from and in which name it is registered - I don't know! Maybe @nesnoj knows this!

**Comment by 4lm** [comment]
Hi @nesnoj,

I updated the attribution (used @christian-rli commit as template). But we have four maps in total (the user can choose from): https://github.com/rl-institut/WAM_APP_stemp_abw/blob/dev/config/leaflet.py#L8-L30

Can you confirm, that the attribution for the other 3 tile server is correct?

For example "OSM B&W" uses the tile server "toolserver.org" but is solely attributed with "Leaflet, OpenStreetMap, CC-BY-SA, 2.0" ...

**Comment by nesnoj** [comment]
Most parts fixed in 8872cc34d3066473653a73f5ed6938ee045d56eb
But the token issue is left (see https://github.com/rl-institut/WAM_APP_FRED/issues/95) and maybe the toolserver.org stuff

**Comment by 4lm** [comment]
@nesnoj, I added our own wam-rli mapbox token. Works as expected!

**Comment by nesnoj** [comment]
Thx!
