### ISSUE TITLE
Get BMBF logo approval

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM_APP_stemp_abw#80]

**Comment by nesnoj** [comment]
The screenshots on the landing page use the old logo.
@AnyaHe Could you please make new screenshots using the [current version on WAM](https://wam.rl-institut.de/) and replace the old ones [here](https://github.com/rl-institut/WAM_APP_stemp_abw/tree/fix/update_screenshots_on_landing_page/static/stemp_abw/img/tool)? (please use the brnch in this link)
(PNG, horizontal resolution: 1000px)

**Comment by nesnoj** [comment]
Addition:
@AnyaHe, the [screenies in the docs](https://github.com/rl-institut/WAM_APP_stemp_abw/tree/fix/update_screenshots_on_landing_page/doc/files) are also affected, could you replace them too, please?

**Comment by AnyaHe** [comment]
I replaced the screenshots on the landing page as described and the ones in the documentation as described in #84.

**Comment by nesnoj** [comment]
Thx a lot @AnyaHe
