### ISSUE TITLE
Share of RE empty in info layer popup

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM_APP_stemp_abw#82]
In the popup of layer "Anteil Energie aus EE an Strombedarf" the relative share (%) of technologies is shown correctly in the chart but missing/empty on mouseover:

![image](https://user-images.githubusercontent.com/15910173/64025917-07284000-cb3e-11e9-9e92-718e1d912234.png)

**Comment by 4lm** [comment]
Minor issue, fixed in: https://github.com/rl-institut/WAM_APP_stemp_abw/commit/0173e8ed2174e29647fb94e5c3842473e18e0d49

**Comment by 4lm** [comment]
Please review and close this issue if satisfied - thx!

**Comment by nesnoj** [comment]
Thx!
