### ISSUE TITLE
Reduce screenshot size in usage docs

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM_APP_stemp_abw#84]
To allow for faster image loading, please update the [screenshot files](https://github.com/rl-institut/WAM_APP_stemp_abw/tree/dev/doc/files) in [usage docs](https://github.com/rl-institut/WAM_APP_stemp_abw/blob/dev/doc/usage.rst):

- [x] reduce width to 1600px
- [x] convert png to jpg (quality 90)
- [x] also, avoid "Umlaute" in file names (even better: english names)

Thx! :)

**Comment by AnyaHe** [comment]
Only the files in usage docs or also other screenshots?

**Comment by nesnoj** [comment]
Usage should be enough, the other files are small enough..

**Comment by nesnoj** [comment]
Hmm, now they are even larger that before...?!

**Comment by AnyaHe** [comment]
Sorry, don't know what happened there. I changed the files. They should be smaller now.

**Comment by nesnoj** [comment]
Looks good, cheers! :)
